_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 66b5bd11-f345-42e4-8a9c-fc2a7b11764b
name: 'Learning Drupal as a framework'
mail: noreply@stefvanlooveren.me
slogan: 'A book by Stefvanlooveren.me'
page:
  403: ''
  404: ''
  front: /offer
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
