/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
CKEDITOR.plugins.add('route_demo', {
    init: function( editor ) {
        if ( editor.ui.addButton ) {
            editor.ui.addButton( 'anand', {
                label: 'default ckeditor button',
                id: 'anand',
                command: '',
                toolbar: 'anand,10',
            } );
        }
    }
} );
