<?php

/**
 * @file
 * Contains custom_plugin.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_plugin_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_plugin module.
    case 'help.page.custom_plugin':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      return $output;

    default:
  }
}

function log_to_file($text) {
  $f = fopen('my_log.txt', 'a');
  fwrite($f, date('Ymd H:i:s - ') . $text . "\n");
  fclose($f);
}

/**
 * Implements hook_theme().
 */
function custom_plugin_theme() {
  $theme = [];
  $theme['default_entity'] = [
    'render element' => 'elements',
    'file' => 'default_entity.page.inc',
    'template' => 'default_entity',
  ];
  $theme['default_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'default_entity.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function custom_plugin_theme_suggestions_default_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#default_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'default_entity__' . $sanitized_view_mode;
  $suggestions[] = 'default_entity__' . $entity->bundle();
  $suggestions[] = 'default_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'default_entity__' . $entity->id();
  $suggestions[] = 'default_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
